# -*- coding: utf-8 -*-
"""Pragya.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jnn_fXbMITgg9-SgnYyIKplRPVBw2I3X

**Pragya Currency ML Model **

---

Prerequisites
"""

!pip install tflite-model-maker

"""Import the required packages."""

import os

import numpy as np

import tensorflow as tf
assert tf.__version__.startswith('2')

from tflite_model_maker import configs
from tflite_model_maker import ExportFormat
from tflite_model_maker import image_classifier
from tflite_model_maker import ImageClassifierDataLoader
from tflite_model_maker import model_spec

import matplotlib.pyplot as plt

"""**Get the data path**
Let's get some images to play with this simple end-to-end example.
"""

import keras
image_path = '/content/drive/Shareddrives/Pragya/Final Dataset/Currency'

"""**Step 1.** Load input data specific to an on-device ML app. Split it to training data and testing data."""

data = ImageClassifierDataLoader.from_folder(image_path)
train_data, test_data = data.split(0.99)

"""**Step 2.** Customize the TensorFlow model."""

model = image_classifier.create(train_data)

"""**Step 3.** Evaluate the model."""

loss, accuracy = model.evaluate(test_data)

"""**Step 4.** Export to TensorFlow Lite model."""

model.export(export_dir='.')